basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'
urlpatterns = [
     path('', views.basket_summary, name='basket-summary'),
     path('add/item/<int:pk>/', views.basket_add, name='basket-add'),
     path('delete/item/<int:pk>/', views.basket_delete, name='basket-delete')
]

delivery_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('food.urls')),
     path('account/', include('users.urls')),
     path('basket/', include('basket.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/add/', views.category_create, name='category-add'),
    path('categories/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('items', views.ItemListView.as_view(), name='all-items'),
    path('items/add/', views.item_create, name='item-add'),
    path('items/delete/', views.ItemsDeletionView.as_view(), name='items-for-deletion'),
    path('items/<int:pk>/', views.ItemDetail.as_view(), name='item-detail'),
    path('items/<int:pk>/delete/', views.item_delete, name='item-delete'),
    path('restaurants/<slug:slug>/', views.RestaurantView.as_view(), name='restaurant'),
    path('restaurants/<slug:slug>/info', views.RestaurantSellInfoView.as_view(), name='restaurant-items-info'),
    path('orders/<int:pk>/update/', views.order_update, name='order-update'),
    path('orders/create', views.order_create, name='order-create')
]

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from food.models import Item


@login_required
def basket_summary(request):
    basket_info = {int(id_): value['quantity'] for id_, value in request.session['item'].items()}
    items = {}
    for id_ in basket_info:
        item = items[id_] = Item.objects.get(id=id_)
        total_price = item.price * basket_info[id_]
        item.total_price = total_price
        item.quantity = basket_info[id_]
        item.save()
    else:
        context = {'items': items}
        return render(request, 'basket/basket_summary.html', context)


@login_required
def basket_add(request, pk):
    if request.method == 'POST':
        item = get_object_or_404(Item, id=pk)
        basket = request.session.get('item', {})
        pk = str(pk)
        if pk not in basket:
            basket[pk] = {'price': str(item.price)}
            basket[pk]['quantity'] = 1
        else:
            basket[pk]['quantity'] += 1
        request.session.modified = True
        return redirect('basket:basket-summary')


@login_required
def basket_delete(request, pk):
    if request.method == 'POST':
        pk = str(pk)
        item = request.session['item'][pk]
        item['quantity'] -= 1
        if item['quantity'] <= 0:
            del request.session['item'][pk]
        request.session.modified = True
        return redirect('basket:basket-summary')

basket/templates/basket/basket_summary.html
{% extends 'food/base.html' %}


{% block title %}
    Basket Summary
{% endblock title %}

{% block content %}
<main class="pt-5 my-3 mx-5">
  <div class="container">
    {% if items %}
    <h1 class="h5">Food basket</h1>
    {% for item in items.values %}

    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ item.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{% url 'food:restaurant' item.owner.slug %}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2 text-center">Restaurant : <small>{{item.owner}} </small></h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">{{item.name}}</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">{{ item.price }} $</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label >Quantity</label>
                {{item.quantity}}

                <form method="post" action="{% url 'basket:basket-add' item.id %}" style="display:inline-block;">
                  {% csrf_token %}
                  <button type="submit"
                    class="btn btn-outline-secondary btn-sm update-button">
                    Add
                  </button>
                </form>
                <form method="post" action="{% url 'basket:basket-delete' item.id %}" style="display:inline-block;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-secondary btn-sm delete-button">
                    Delete
                  </button>
                </form>
                <small style="float:right"> total price: {{item.total_price}} $</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
    <div class="h5 fw-bold" style="float:right">
      <a href="{% url 'food:all-items' %}">
        <button type="button" class="btn btn-outline-primary btn-sm delete-button" style="width:160px;height:40px">
          Select more items
        </button>
      </a>
        Sub Total: {{sub_total_price}} $
    </div>
    <div class="h5 fw-bold" style="float:right">
      <div class="text-end">
          <div class="my-5">
            <form method="post" action="{% url 'food:order-create' %}">
              {%csrf_token%}
              <label for="phone">Contect: </label>
              <input type="text" name="phone" id="phone" required style="height:40px; width:400px" placeholder="Phone number">
              <label for="adress">Adress: </label>
              <input type="text" name="adress" id="adress" required style="height:40px; width:400px" placeholder="Enter your adress">
              <button type="submit" class="btn btn-outline-primary btn-sm delete-button" style="width:120px;height:40px">
                Order
              </button>
            </form>
          </div>
      </div>
    </div>
    {% else %}
    <h3 class="text-center">You did not choose any item</h3>
    {% endif %}
  </div>


</main>
{% endblock content %}