basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'
urlpatterns = [
     path('', views.basket_summary, name='basket-summary'),
     path('add/item/<int:pk>/', views.basket_add, name='basket-add'),
     path('delete/item/<int:pk>/', views.basket_delete, name='basket-delete')
]

delivery_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('food.urls')),
     path('account/', include('users.urls')),
     path('basket/', include('basket.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/add/', views.category_create, name='category-add'),
    path('categories/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('items', views.ItemListView.as_view(), name='all-items'),
    path('items/add/', views.item_create, name='item-add'),
    path('items/delete/', views.ItemsDeletionView.as_view(), name='items-for-deletion'),
    path('items/<int:pk>/', views.ItemDetail.as_view(), name='item-detail'),
    path('items/<int:pk>/delete/', views.item_delete, name='item-delete'),
    path('restaurants/<slug:slug>/', views.RestaurantView.as_view(), name='restaurant'),
    path('restaurants/<slug:slug>/info', views.RestaurantSellInfoView.as_view(), name='restaurant-items-info'),
    path('orders/<int:pk>/update/', views.order_update, name='order-update'),
    path('orders/create', views.order_create, name='order-create')
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
     path('register/', views.user_register, name='register'),
     path('register/restaurnat', views.restaurant_register, name='restaurant-register'),
     path('login/', views.user_login, name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
     path('dashboard/<int:year>/<str:month>/<int:day>/', views.DailyDashboardView.as_view(), name='dashboard'),
     path('profile/', views.profile, name='profile')
]

food/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from PIL import Image

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Restaurant(models.Model):

    DAYS = (
        ('Mn', 'Monday'),
        ('Ts', 'Tuesday'),
        ('Wd', 'Wednesday'),
        ('Thr', 'Thursday'),
        ('Fr', 'Friday'),
        ('St', 'Saturday'),
        ('Sn', 'Sunday')
    )

    name = models.CharField(max_length=250, unique=True)
    open_at = models.TimeField()
    close_at = models.TimeField()
    day_off = models.CharField(max_length=32, choices=DAYS, default='Sn')
    contact = models.CharField(max_length=32)
    email = models.EmailField()
    slug = models.SlugField()

    def __str__(self):
        return self.name


def custom_dir_path(instance, filename):
    return f'{instance.__class__.__name__.lower()}/{filename}'


class Adress(models.Model):
    CITIES = (
        ('Tashkent', 'Tashkent'),
        ('Andijan', 'Andijan'),
        ('Namangan', 'Namangan'),
        ('Fergana', 'Fergana'),
        ('Karshi', 'Karshi'),
        ('Termiz', 'Termiz'),
        ('Nukus', 'Nukus'),
        ('Samarkand', 'Samarkand'),
        ('Navai', 'Navai'),
        ('Bukhara', 'Bukhara'),
        ('Khorezm', 'Khorezm'),
        ('Jizzakh', 'Jizzakh')
    )
    city = models.CharField(max_length=64, choices=CITIES, default='Tashkent')
    district = models.CharField(max_length=250)
    place = models.OneToOneField(Restaurant, null=True, related_name='adress', on_delete=models.SET_NULL)

    def __str__(self):
        return self.district

    class Meta:
        verbose_name_plural = 'Adresses'


class Item(models.Model):
    RATINGS = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to=custom_dir_path)
    slug = models.SlugField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    owner = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATINGS, null=True, blank=True)
    total_price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)
    num_of_sold = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('food:item-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        size = (250, 250)
        img.thumbnail(size)
        img.save(self.image.path)


class Order(models.Model):
    ORDER_STATUS = (
        ('done', 'completed'),
        ('delivering', 'on the way'),
        ('preparing', 'being cooked')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, related_name='orders',)
    adress = models.CharField(max_length=250)
    phone = models.CharField(max_length=20, null=True, default=None)
    total_price = models.DecimalField(max_digits=11, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=32, choices=ORDER_STATUS, default='preparing')

    def all_items(self):
        items = ''
        for item in self.items.all():
            items += f'{item.name} : {item.quantity} '
        return items

    @property
    def item_owner(self):
        return self.items.all().first().owner

    def __str__(self):
        return f'Order by {self.user.user_name}'

food/forms.py
from django import forms
from .models import Category


class ItemCreationForm(forms.Form):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Name'})
        self.fields['price'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Price'})
        self.fields['category'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Category'})
        self.fields['category'].queryset = Category.objects.filter(user=user)

    name = forms.CharField()
    price = forms.DecimalField(max_digits=10, decimal_places=2)
    category = forms.ModelChoiceField(queryset=None)
    image = forms.ImageField()


class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

food/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from users.models import NewUser
from .models import Item, Restaurant, Category, Order
from .forms import ItemCreationForm, CategoryCreationForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from datetime import date
from django.urls import reverse


class HomeView(ListView):
    template_name = 'food/index.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Item.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['category_names'] = list({category.name for category in Category.objects.all()
                                          if Item.objects.filter(category__name=category.name).exists()})
        context['categories'] = Category.objects.all()
        return context


class ItemListView(ListView):
    """List of all items to make an order """

    template_name = 'food/all_items.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Item.objects.all().order_by('price')


class ItemDetail(DetailView):
    template_name = 'food/item.html'
    context_object_name = 'item'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return Item.objects.all()


class CategoryView(ListView):
    template_name = 'food/category.html'
    context_object_name = 'items'

    def get_queryset(self):
        category = Category.objects.filter(name__iexact=(self.kwargs['category'])).first()
        return Item.objects.filter(category__name__iexact=category.name)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        category = Category.objects.filter(name__iexact=self.kwargs['category']).first()
        context['category'] = category
        restaurant_names = [res.name for res in Restaurant.objects.all()]
        users = NewUser.objects.all()
        res_users = [user for user in users if user.user_name in restaurant_names and
                     Item.objects.filter(owner__name=user.user_name).
                     filter(category__name__iexact=(self.kwargs['category'])).exists()]
        context['restaurants'] = res_users
        return context


class RestaurantView(ListView):
    template_name = 'food/restaurant.html'
    context_object_name = 'items'

    def get_queryset(self):
        restaurant = Restaurant.objects.get(slug=self.kwargs['slug'])
        return Item.objects.filter(owner=restaurant)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        restaurant = Restaurant.objects.get(slug=self.kwargs['slug'])
        context['restaurant'] = restaurant
        context['categories'] = Category.objects.filter(user__user_name=restaurant.name)
        return context


class RestaurantSellInfoView(UserPassesTestMixin, ListView):
    """ This view is only for restaurant users.
        They can see items info about times of sold  """

    def test_func(self):
        return self.request.user.groups.filter(name='Restaurants').exists()

    def handle_no_permission(self):
        return JsonResponse({'message': 'Only restaurants can access this view'})

    template_name = 'food/restaurant_sell_info.html'
    context_object_name = 'items'

    def get_queryset(self):
        restaurant = Restaurant.objects.get(slug=self.kwargs['slug'])
        return Item.objects.filter(owner=restaurant).order_by('-num_of_sold')


def user_in_restaurant_group(user):
    if user:
        return user.groups.filter(name='Restaurants').exists()


today = {
         'year': int(date.today().strftime('%Y')),
         'month': date.today().strftime('%b'),
         'day': date.today().strftime('%d')
        }


@user_passes_test(user_in_restaurant_group, login_url='food:home')
def item_create(request):

    """ Only restaurant users can create item """

    if request.method == 'POST':
        form = ItemCreationForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            category = form.cleaned_data['category']
            image = form.cleaned_data['image']
            restaurant = Restaurant.objects.get(name=request.user.user_name)
            item = Item(name=name, price=price, category=category, image=image, owner=restaurant)
            item.slug = slugify(name)
            item.save()
            return redirect(reverse('accounts:dashboard', kwargs={**today}))
        return render(request, 'food/add_item.html', {'form': form})

    """ Pass user to a form to assign item's category
     from categories that user created and not others """

    form = ItemCreationForm(user=request.user)
    return render(request, 'food/add_item.html', {'form': form})


@user_passes_test(user_in_restaurant_group, login_url='food:home')
def item_delete(request, pk):

    """ Only restaurant users can create item """

    if request.method == 'POST':
        item = Item.objects.get(id=pk)
        if item.owner.name == request.user.user_name:
            for order in Order.objects.all():
                order.items.remove(item)
                if order.items.all().count() <= 0:
                    order.delete()
            item.delete()
            return redirect(reverse('food:items-for-deletion'))
        else:
            return JsonResponse({
                'message': 'You have no authority to delete this item'
            })
    else:
        return redirect('food:items-for-deletion')


class ItemsDeletionView(UserPassesTestMixin, ListView):

    def test_func(self):
        return self.request.user.groups.filter(name='Restaurants').exists()

    def handle_no_permission(self):
        return JsonResponse({'message': 'Only restaurants can access this view'})

    template_name = 'food/items_deletion.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Item.objects.filter(owner__name=self.request.user.user_name)


@user_passes_test(user_in_restaurant_group, login_url='food:home')
def category_create(request):
    if request.method == 'POST':
        form = CategoryCreationForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect(reverse('accounts:dashboard', kwargs={**today}))
        return render(request, 'food/category_add.html', {'form': form})
    form = CategoryCreationForm()
    return render(request, 'food/category_add.html', {'form': form})


@login_required
def order_update(request, pk):
    """
    If restaurant clicks ready button order status changes from preparing to delivering.
    If orderer takes his order and clicks ready button, order is done and for each item
    in order increase num of sold time
    """
    order = Order.objects.get(pk=pk)
    if request.user.groups.filter(name='Restaurants').exists():
        owners = [item.owner.name for item in order.items.all()]
        if request.method == 'POST':
            if request.user.user_name in owners:
                if 'ready' in request.POST:
                    order.status = 'delivering'
                    order.save()
                if 'cancel' in request.POST:
                    order.delete()
                return redirect(reverse('accounts:dashboard', kwargs={**today}))
    else:
        if request.method == 'POST':
            if order.user == request.user:
                if 'ready' in request.POST:
                    order.status = 'done'
                    items = order.items.all()
                    for item in items:
                        item.num_of_sold += item.quantity
                        item.save()
                    else:
                        order.save()

                if 'cancel' in request.POST:
                    order.delete()
                return redirect(reverse('accounts:dashboard', kwargs={**today}))
        return redirect(reverse('accounts:dashboard', kwargs={**today}))


@login_required
def order_create(request):
    if request.method == 'POST':
        basket = request.session['item']
        adress = request.POST.get('adress')
        phone = request.POST.get('phone')
        items_id = [int(id_) for id_ in basket]
        items = [Item.objects.get(id=id_) for id_ in items_id]
        restaurants = {}
        for item in items:
            if item.owner not in restaurants:
                restaurants[item.owner] = {item.id: item}
            else:
                restaurants[item.owner][item.id] = item

        for restaurant in restaurants.values():
            restaurant_items = [item for item in restaurant.values()]
            total_price = sum(map(lambda item_: item_.total_price, restaurant_items))
            order = Order.objects.create(user=request.user, adress=adress, phone=phone, total_price=total_price)
            for item in restaurant_items:
                order.items.add(item)
            order.save()

        request.session['item'] = {}
        request.session.modified = True
        return redirect(reverse('accounts:dashboard', kwargs={**today}))

food/templates/food/add_item.html
{% extends 'food/base.html' %}

{% block title %}
    Add item
{% endblock title %}
{% block content %}

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                        <form class="account-form p-4 rounded col-lg-10 mx-auto" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h3 class="mb-2 font-weight-bold">Add Item</h3>
                        {% if form.errors %}
                        <p>Please correct the following errors:</p>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-primary" role="alert">
                            {{ field.label }}: {{ field.errors|striptags }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        {{form.as_p}}

                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Create</button>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

food/templates/food/all_items.html
{% extends 'food/base.html' %}


{% block title %}
    All Items
{% endblock title %}

{% block content %}
<main class=" mx-5">
  <h2 class="text-center my-5">All Items</h2>
  <div class="container">
    {% for item in items %}
    <div  class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <a href="{{item.get_absolute_url}}">
          <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ item.image.url }}">
        </a>
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{% url 'food:restaurant' item.owner.slug %}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2 text-center"><small>Restaurant : {{item.owner}}</small></h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Name : {{item.name}}</div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12 d-inline-flex">
                <h6>Price : {{item.price}} $</h6>
                <form method='post' action="{%  url 'basket:basket-add' item.id %}" class="mx-5">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-primary">
                    Add to basket
                  </button>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block content %}

{% for name in category_names %}

  <div class="my-3 mx-5 bg-secondary sticky-top"
       style="height:30px;top:68px;z-index:30;">
    <a href="{% url 'food:category' name|lower %}">
      <h5 class="mx-5" style="color:white">{{name}}</h5>
    </a>
  </div>
  <div class="album py-5 my-3 mx-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for item in items %}
        {% if item.category.name == name %}
        <div class="col-md-3">
          <div class="card shadow-sm">
            <img class="img-fluid card-img-top" alt="Responsive image" src="{{ item.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ item.get_absolute_url }}">
                  <button class="btn btn-sm btn-light">{{item.name}}</button>
                </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small>Restaurant : {{item.owner}}</small>
              </div>
              <div>
                <small>Price : {{item.price}} $</small>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>

{% endfor %}



{% endblock content %}

food/templates/food/item.html
{% extends 'food/base.html' %}

{% block title %}
    {{item.name}}
{% endblock title %}
{% block content %}


<div class="container my-3 mx-5">
    <main class="pt-5 ">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto card-img-top d-block" width="200px" alt="Responsive image" src="{{ item.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ item.name }}</h1>
                <p><span class="lead">{{ item.owner }}</span> (Restaurant)</p>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ item.price }} $</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">

                              <form method="post" action="{% url 'basket:basket-add' item.id %}">
                                {% csrf_token %}
                                <button type="submit" id="add-button" value="{{item.id}}" style="float:right"class="btn m-2 btn-primary btn-sm">Add to basket</button>
                               </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

{% endblock content %}

food/templates/food/items_deletion.html
{% extends 'food/base.html' %}


{% block title %}
    Delete Items
{% endblock title %}

{% block content %}
<main class=" mx-5">
  <h2 class="text-center my-5">Delete Items</h2>
  <div class="container">
    {% for item in items %}
    <div  class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <a href="{{item.get_absolute_url}}">
          <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ item.image.url }}">
        </a>
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{% url 'food:restaurant' item.owner.slug %}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2 text-center"><small>Restaurant : {{item.owner}}</small></h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Name : {{item.name}}</div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12 d-inline-flex">
                <h6>Price : {{item.price}} $</h6>
                <form method='post' action="{%  url 'food:item-delete' item.id %}" class="mx-5">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-danger">
                    Delete item
                  </button>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
{% endblock %}

food/templates/food/navbar.html
<nav class="navbar my-3 mx-5 sticky-top navbar-expand-lg  bg-secondary">

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" style="color:white" href="{% url 'food:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color:white" href="{% url 'food:all-items' %}">Items</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% for category_name in all_category_names %}
          <a class="dropdown-item" href="{% url 'food:category' category_name|lower %}">{{category_name}}</a>
          {% endfor %}
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color:white" href="" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Restaurants
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% for restaurant in all_restaurants %}
          <a class="dropdown-item" href="{% url 'food:restaurant' restaurant.slug %}">{{restaurant}}</a>
          {% endfor %}
        </div>
      </li>
    </ul>
  </div>
    <ul class="nav justify-content-end">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link " style="color:white" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        {% now "Y" as current_year %}
        {% now "M" as current_month %}
        {% now "d" as current_day %}
        <a class="nav-link " style="color:white"
           href="{% url 'accounts:dashboard' year=current_year month=current_month day=current_day %}">
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " style="color:white" href="{% url 'accounts:profile' %}">
          <img class="rounded-circle article-img" src="{{ request.user.profile.image.url }}" alt="{{request.user.user_name}}" id="img">
          <small>{{request.user.user_name}}</small>
        </a>
      </li>
      <li class="nav-item">
        <a class="btn btn-light"  type="button" role="button" href="{% url 'basket:basket-summary' %}">
          <div class="d-inline-flex">{% if total_basket_items != 0 %}{{total_basket_items}}{% endif %}</div>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
          <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg>
          <small>Basket</small>
        </a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link active" style="color:white" href="{% url 'accounts:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color:white" href="{% url 'accounts:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color:white" href="{% url 'accounts:restaurant-register' %}">Register as a restaurant</a>
      </li>
      {% endif %}
    </ul>
</nav>

food/templates/food/restaurant.html
{% extends 'food/base.html' %}

{% block title %}
{{restaurant}}
{% endblock title %}
{% block content %}
  <div class="my-3 mx-5 bg-secondary sticky-top"
       style="height:30px;top:68px;z-index:30;">
      <h5 class="mx-5" style="color:white">{{restaurant}}</h5>
  </div>
{% for category in categories %}
{% if category.items.all|length > 0 %}
  <div class="my-3 mx-5 bg-secondary sticky-top"
       style="height:30px;top:99px;z-index:30;">
    <a href="{% url 'food:category' category.name|lower %}">
      <h5 class="mx-5" style="color:white">{{category}}</h5>
    </a>
  </div>
    <div class="album py-5 my-3 mx-5 bg-light">
        <div class="container">

            <div class="row">
        {% for item in items %}
        {% if item.category.name == category.name %}
            <div class="col-md-4">
                <a class="text-dark" href="{{ item.get_absolute_url }}">
                   <div class="card mb-4 box-shadow">
                       <img class="card-img-top" src="{{ item.image.url }}" alt="{{ item.name }}">
                       <div class="card-only">
                           <h2 style="font-size:18px;font-weight:bold;margin:15px" class="d-inline-flex">
                               {{ item.name }} : {{item.price}} $
                           </h2>
                       </div>
                   </div>
                </a>
            </div>
        {% endif %}
        {% endfor %}
            </div>
        </div>
    </div>
{% endif %}
{% endfor %}

{% endblock content %}

food/templates/food/restaurant_sell_info.html
{% extends 'food/base.html' %}
{% load mathfilters %}

{% block title %}
    Items Info
{% endblock title %}

{% block content %}
<main class=" mx-5">
  <h2 class="text-center my-5">Items Info</h2>
  <div class="container">
    {% for item in items %}
    <div  class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <a href="{{item.get_absolute_url}}">
          <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ item.image.url }}">
        </a>
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{% url 'food:restaurant' item.owner.slug %}" class="text-decoration-none text-reset">
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6 d-flex-inline">Name : {{item.name}}</div>
              <div class="col-6 ">Price : {{item.price}} $</div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6 d-inline-flex">Sold : {{item.num_of_sold}} times</div>
                <div class="col-6">
                  Total paid : {{ item.price|mul:item.num_of_sold }} $
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
{% endblock %}