delivery_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('food.urls')),
     path('account/', include('users.urls')),
     path('basket/', include('basket.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/add/', views.category_create, name='category-add'),
    path('categories/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('items', views.ItemListView.as_view(), name='all-items'),
    path('items/add/', views.item_create, name='item-add'),
    path('items/delete/', views.ItemsDeletionView.as_view(), name='items-for-deletion'),
    path('items/<int:pk>/', views.ItemDetail.as_view(), name='item-detail'),
    path('items/<int:pk>/delete/', views.item_delete, name='item-delete'),
    path('restaurants/<slug:slug>/', views.RestaurantView.as_view(), name='restaurant'),
    path('restaurants/<slug:slug>/info', views.RestaurantSellInfoView.as_view(), name='restaurant-items-info'),
    path('orders/<int:pk>/update/', views.order_update, name='order-update'),
    path('orders/create', views.order_create, name='order-create')
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
     path('register/', views.user_register, name='register'),
     path('register/restaurnat', views.restaurant_register, name='restaurant-register'),
     path('login/', views.user_login, name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
     path('dashboard/<int:year>/<str:month>/<int:day>/', views.DailyDashboardView.as_view(), name='dashboard'),
     path('profile/', views.profile, name='profile')
]

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from PIL import Image


class CustomAccountManager(BaseUserManager):

    def create_user(self, email, user_name, password, first_name=None, **other_fields):
        if not email:
            raise ValueError('You must provide an email adress')

        email = self.normalize_email(email)
        user = self.model(email=email, user_name=user_name, first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, user_name, password, first_name=None, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, user_name, password, first_name, **other_fields)


class NewUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    user_name = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    start_date = models.DateTimeField(default=timezone.now)
    about = models.TextField(max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name', 'password']

    def __str__(self):
        return self.user_name


def custom_user_dir(instance, filename):
    return f'profiles/{instance.user.id}/{filename}'


class Profile(models.Model):
    user = models.OneToOneField(NewUser, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(default='default.jpeg', upload_to=custom_user_dir)

    def __str__(self):
        return f'{self.user.user_name} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            size = (300, 300)
            img.thumbnail(size)
            img.save(self.image.path)

users/forms.py
from django import forms
from .models import NewUser, Profile
from food.models import Restaurant, Adress


class RegistrationForm(forms.Form):
    user_name = forms.CharField(label='Enter username', help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={'required': 'Email is required'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    def clean_user_name(self):
        user_name = self.cleaned_data['user_name'].lower()
        r = NewUser.objects.filter(user_name=user_name)
        if r.count():
            raise forms.ValidationError('User with this username already exists')
        return user_name

    def clean_password2(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords do not match')
        return self.cleaned_data['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if NewUser.objects.filter(email=email).exists():
            raise forms.ValidationError('User with this email already exists')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Repeat Password'})


class UserLoginForm(forms.Form):
    user_name = forms.CharField(label='Enter username', help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={'required': 'Email is required'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})


class RestaurantRegisterForm(forms.ModelForm):
    city = forms.ChoiceField(choices=Adress.CITIES, initial='Tashkent')
    district = forms.CharField(max_length=64)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password2', widget=forms.PasswordInput)

    class Meta:
        model = Restaurant
        fields = ('name', 'email', 'password', 'password2', 'open_at',  'close_at', 'day_off', 'contact')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Name'})
        self.fields['open_at'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Open at'})
        self.fields['close_at'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Close at'})
        self.fields['day_off'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Day off'})
        self.fields['contact'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Phone number'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Repeat Password'})
        self.fields['city'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'City'})
        self.fields['district'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'District'})

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords do not match')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = NewUser
        fields = ['user_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Email'})


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
import datetime
from django.shortcuts import render, redirect
from .forms import RegistrationForm, UserLoginForm, RestaurantRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import NewUser, Profile
from django.contrib.auth import login
from django.contrib.auth.models import Group
from food.models import Adress, Restaurant
from django.utils.text import slugify
from django.views.generic import ListView
from django.urls import reverse
from datetime import date
from food.models import Order


def user_register(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            name = register_form.cleaned_data['user_name']
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password']
            user = NewUser(user_name=name, email=email)
            user.set_password(password)
            user.is_active = True
            user.save()
            return redirect('accounts:login')
        return render(request, 'users/register.html', {'form': register_form})
    register_form = RegistrationForm()
    return render(request, 'users/register.html', {'form': register_form})


def user_login(request):
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            email = login_form.cleaned_data['email']
            user = NewUser.objects.filter(email=email).first()
            if user:
                if user.check_password(login_form.cleaned_data['password']):
                    login(request, user)
                    return redirect(reverse('accounts:dashboard', kwargs={
                                                                         'year': int(date.today().strftime('%Y')),
                                                                         'month': date.today().strftime('%b'),
                                                                         'day': date.today().strftime('%d')
                                                                         }))
            return render(request, 'users/login.html', {
                                                        'form': login_form,
                                                        'message': 'Email or Password is wrong. Please, try again'
                                                        })
    else:
        login_form = UserLoginForm()
        return render(request, 'users/login.html', {'form': login_form})


def restaurant_register(request):
    if request.method == 'POST':
        form = RestaurantRegisterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            open_at = form.cleaned_data['open_at']
            close_at = form.cleaned_data['close_at']
            day_off = form.cleaned_data['day_off']
            contact = form.cleaned_data['contact']
            city = form.cleaned_data['city']
            district = form.cleaned_data['district']
            restaurant = Restaurant(name=name, email=email, close_at=close_at,
                                    open_at=open_at, contact=contact, day_off=day_off)
            restaurant.slug = slugify(name)
            restaurant.save()
            address = Adress.objects.create(city=city, district=district, place=restaurant)
            user = NewUser(user_name=name, email=email)
            user.set_password(password)
            user.is_active = True
            user.save()
            restaurant_group = Group.objects.get(name='Restaurants')
            restaurant_group.user_set.add(user)
            return redirect('accounts:login')
        return render(request, 'users/restaurant_register.html', {'form': form})
    form = RestaurantRegisterForm()
    return render(request, 'users/restaurant_register.html', {'form': form})


class DailyDashboardView(LoginRequiredMixin, ListView):
    """
        Show orders daily for users and restaurants accordingly.
        get_context_data takes all dates for user if user has order on that date
    '"""

    template_name = 'users/dashboard.html'
    context_object_name = 'orders'

    def get_queryset(self):
        year = self.kwargs['year']
        month = self.kwargs['month']
        day = self.kwargs['day']
        requested_date = datetime.datetime.strptime(f"{year} {month} {day}", '%Y %b %d')
        res_group = Group.objects.get(name='Restaurants')
        if res_group in self.request.user.groups.all():
            return set(Order.objects.filter(items__owner__name=self.request.user.user_name).\
                                 filter(date__date=requested_date.date()).order_by('-date'))

        return Order.objects.filter(user=self.request.user).\
                             filter(date__date=requested_date.date()).order_by('-date')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        res_group = Group.objects.get(name='Restaurants')
        if res_group in self.request.user.groups.all():
            context['restaurant'] = Restaurant.objects.get(name=self.request.user.user_name)
            context['dates'] = Order.objects.filter(items__owner__name=self.request.user.user_name).dates('date', 'day')
        else:
            context['dates'] = Order.objects.filter(user=self.request.user).dates('date', 'day')
        return context


@login_required
def profile(request):
    user = request.user
    profile_ = Profile.objects.get(user=user)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=profile_)
        if u_form.is_valid():
            if p_form.is_valid():
                u_form.save()
                p_form.save()
                return redirect('accounts:profile')
        context = {
                 'profile': profile_,
                 'u_form': u_form,
                 'p_form': p_form
                }
        return render(request, 'users/profile.html', context)
    u_form = UserUpdateForm(instance=user)
    p_form = ProfileUpdateForm(instance=profile_)
    context = {
                'profile': profile_,
                'u_form': u_form,
                'p_form': p_form
            }
    return render(request, 'users/profile.html', context)

users/templates/users/dashboard.html
{% extends 'food/base.html' %}
{% block title %}
Dashboard
{% endblock title %}
{% block content %}
   <div style="float:right; margin-right:95px; width:200px">
    <div class="ml-15">
      <h5 class="text-primary" >Order History</h5>
      <input id="hide" onclick="Myfunction()" type="button" value="hide" class="btn btn-sm btn-light text-primary"/>
    </div>
    <aside id="sidebar"  style="margin-right:25px; margin-top:15px; background-color:rgb(180,180,180); width:150px;">
      <div class="text-center">
        {% for date in dates %}
        <div>
          <a href="{% url 'accounts:dashboard' date.year date|date:'M' date.day %}">
            <h6 class="text-center text-primary">{{date|date:"M d, Y"}}</h6>
          </a>
        </div>
            {% endfor %}
        </div>
    </aside>
   </div>
    <div class="album w-75 py-3 mx-5 bg-light" >
        {% if restaurant %}
        <div class="container my-5 mx-7">
        <a href="{% url 'food:category-add' %}">
            <button type="button" class="btn btn-outline-primary">Add Categories</button>
        </a>
        <a href="{% url 'food:item-add' %}">
            <button type="button" class="btn btn-outline-primary">Add Items</button>
        </a>
        <a href="{% url 'food:items-for-deletion' %}">
            <button type="button" class="btn btn-outline-danger">Delete Items</button>
        </a>
        <a style="float:right" href="{% url 'food:restaurant-items-info' restaurant.slug %}">
            <button type="button" class="btn btn-outline-primary">Items Info</button>
        </a>
        </div>


        <div class="container">
          <h3 class="text-center"><b>My Orders</b></h3>
            <div class="row">
             <table style="width:100%" class="my-5">
                <tbody>
                 <tr style="border-bottom: 2px solid black">
                     <th>Customer</th>
                     <th>Products</th>
                     <th>Date</th>
                     <th>Total price</th>
                     <th>Adress</th>
                     <th>Contact</th>
                     <th>Status</th>
                     <th>Update</th>
                 </tr>
                 {% for order in orders %}
                 <tr style="border-bottom: 2px solid black;">
                     <td>{{order.user.user_name}}</td>
                     <td>{{order.all_items}}</td>
                     <td>{{order.date|date:"j F, Y | H:i"}}</td>
                     <td>{{order.total_price}} $</td>
                     <td>{{order.adress}}</td>
                     <td>{{order.phone}}</td>
                     <td>{{order.status}}</td>
                     {% if order.status != 'done' %}
                     <td>
                        <form method="post" action="{% url 'food:order-update' order.id %}" style="display:inline-block;" id="myform">
                           {% csrf_token %}
                           <input type="submit"  class="btn btn-primary" name="ready" value="Ready">
                         </form>
                         <form method="post" action="{% url 'food:order-update' order.id %}" style="display:inline-block;" id="form">
                           {% csrf_token %}
                           <input type="submit" class="btn btn-secondary" name="cancel" value="Cancel">
                         </form>
                     </td>
                     {% else %}
                     <td>finished</td>
                     {% endif %}
                 {% endfor %}
             </table>
            </div>
        </div>
         {% else %}
         <div class="container">
           <h3 class="text-center"><b>My Orders</b></h3>
            <div class="row">
              <table style="width:100%" class="my-5">
                <tbody>
                  <tr style="border-bottom: 2px solid black">
                     <th>Products</th>
                     <th>Restaurant</th>
                     <th>Total price</th>
                     <th>Restaurant Contact</th>
                     <th>Adress</th>
                     <th>Date</th>
                     <th>Status</th>
                     <th>Update</th>
                  </tr>
                {% for order in orders %}

                  <tr style="border-bottom: 2px solid black;">
                     <td>{{order.all_items}}</td>
                     <td>{{order.item_owner}}</td>
                     <td>{{order.total_price}} $</td>
                     <td>{{order.item_owner.contact}}</td>
                     <td>{{order.adress}}</td>
                     <td>{{order.date|date:"j F, Y | H:i"}}</td>
                     <td>{{order.status}}</td>
                     {% if order.status != 'done' %}
                     <td>
                        <form method="post" action="{% url 'food:order-update' order.id %}" style="display:inline-block;" id="myform">
                             {% csrf_token %}
                             <input type="submit"  class="btn btn-primary" name="ready" value="Ready">
                         </form>

                         <form method="post" action="{% url 'food:order-update' order.id %}" style="display:inline-block;" id="form">
                             {% csrf_token %}
                             <input type="submit" class="btn btn-secondary" name="cancel" value="Cancel">
                         </form>
                     </td>
                     {% else %}
                     <td>finished</td>
                     {% endif %}
                {% endfor %}
              </table>
             {% endif %}
            </div>
        </div>
    </div>



<script>
function Myfunction () {
    var aside = document.getElementById("sidebar");
    if (aside.style.display !== "none") {
        aside.style.display = "none";
        document.getElementById("hide").value = "show";
    } else {
      aside.style.display = "block";
      document.getElementById("hide").value = "hide";
    }
}

</script>

{% endblock content %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block title %}
Login
{% endblock title %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                        <form class="account-form p-4 rounded col-lg-10 mx-auto" method="post">
                        {% csrf_token %}
                        <h3 class="mb-2 font-weight-bold">Login</h3>
                        <p class="'text-danger">{{ message }}</p>
                        {% if form.errors %}
                        <p>Please correct the following errors:</p>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-primary" role="alert">
                            {{ field.label }}: {{ field.errors|striptags }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        <label>{{ form.user_name.label }}<span class="text-muted small">(Required)</span></label>
                        {{ form.user_name }}
                        <label>{{ form.email.label }}<span class="text-muted small">(Required)</span></label>
                        {{ form.email }}
                        <label>{{ form.password.label }}<span class="text-muted mb-4"></span></label>

                        {{ form.password }}

                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Login</button>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block title %}
Profile
{% endblock title %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }

     img {
      border-radius: 50%;
    }

</style>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

        <div class="media" style="margin-left:80px; margin-top:80px">
            <img style="border-radius:50%" src="{{ profile.image.url }}">
            <div class="media-body mx-3">
                <h2 class="account-heading">{{ profile.user.user_name }}</h2>
                <p class="text-secondary">{{ profile.user.email }}</p>
            </div>
        </div>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                        <form class="account-form p-4 rounded col-lg-10 mx-auto "
                              method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h3 class="mb-2 font-weight-bold">Update Profile</h3>
                        {% if u_form.errors %}
                        <p>Please correct the following errors:</p>
                        {% for field in u_form %}
                        {% if field.errors %}
                        <div class="alert alert-primary" role="alert">
                            {{ field.label }}: {{ field.errors|striptags }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        <label>{{ u_form.user_name.label }}</label>
                        {{ u_form.user_name }}
                        <label>{{ u_form.email.label }}</label>
                        {{ u_form.email }}
                        <label>{{ p_form.image.label }}</label>
                        {{ p_form.image }}
                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Update</button>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block title %}
Register
{% endblock title %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                        <form class="account-form p-4 rounded col-lg-10 mx-auto" method="post">
                        {% csrf_token %}
                        <h3 class="mb-2 font-weight-bold">Create an account</h3>
                        {% if form.errors %}
                        <p>Please correct the following errors:</p>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-primary" role="alert">
                            {{ field.label }}: {{ field.errors|striptags }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        <label>{{ form.user_name.label }}<span class="text-muted small">(Required)</span></label>
                        {{ form.user_name }}
                        <label>{{ form.email.label }}<span class="text-muted small">(Required)</span></label>
                        {{ form.email }}
                        <label>{{ form.password.label }}<span class="text-muted mb-4"></span></label>
                        {{ form.password }}
                        <label> {{ form.password2.label }}<span class="text-muted small">(Required)</span></label>
                        {{ form.password2 }}
                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Register</button>
                        <p class="text-center">
                            <a href=#>Already have an account?</a>
                        </p>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/restaurant_register.html
{% extends 'food/base.html' %}

{% block title %}
Restaurant Register
{% endblock title %}

{% block content %}
<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                        <form class="account-form p-4 rounded col-lg-10 mx-auto" method="post">
                        {% csrf_token %}
                        <h3 class="mb-2 font-weight-bold">Create an account</h3>
                        {% if form.errors %}
                        <p class="text-danger">Please correct the following errors:</p>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-primary" role="alert">
                            {{ field.label }}: {{ field.errors|striptags }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        {{ form.as_p }}
                        {{ form.adress }}
                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Register</button>

                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}